### ISSUE TITLE
inquirer.select breaks asyncio operations

### ISSUE THREAD

**Issue by sxpmoore** [kazhala/InquirerPy#71]
I ran into a problem where calling this.

```
selection = inquirer.select(message="test this", choices=[Choice("opt1", name="for opt 1"), Choice("opt 2", name="for opt 2")], cycle=False).execute()
```
After calling that select,  all asyncio commands would fail. Here is a demo to reproduce the issue.  The 1st 2 pinghosts call works but not after the inquirer.select

```
import asyncio
from asyncio.subprocess import PIPE, STDOUT
from InquirerPy import inquirer
from InquirerPy.base.control import Choice


async def run_command(*args, host=None):
        process = await asyncio.create_subprocess_exec(*args, stdout=PIPE, stderr=PIPE)
        stdout, stderr = await process.communicate()
        return host, process.returncode == 0

def pinghosts(hosts, verbose=False):  
    jobs = (run_command(*((f'ping -c1 -W1 {host}').split()), host=host) for host in hosts)    
    results = asyncio.get_event_loop().run_until_complete( asyncio.gather( *jobs ) )
    return results


print( pinghosts(['box20', 'box1d2', 'box21']) )
print( pinghosts(['box20', 'box1d2', 'box21']) )

selection = inquirer.select(message="test this", choices=[Choice("opt1", name="for opt 1"), Choice("opt 2", name="for opt 2")], cycle=False).execute()

print( pinghosts(['box20', 'box1d2', 'box21']) )
```

it fails with this 

Traceback (most recent call last):
  File "./demo.py", line 25, in <module>
    print( pinghosts(['box20', 'box1d2', 'box21']) )
  File "./demo.py", line 16, in pinghosts
    results = asyncio.get_event_loop().run_until_complete( asyncio.gather( *jobs ) )
  File "/usr/lib64/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

Is this my bug or a bug in how inquirer.select().exeute() operates ?

**Comment by sxpmoore** [comment]
I found a workaround to open a new event loop.

```
def pinghosts(hosts): 
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    jobs = (run_command(*((f'ping -c1 -W1 {host}').split()), host=host) for host in hosts)    
    results = loop.run_until_complete( asyncio.gather( *jobs ) )
    return results
```

However, I'm not confident of this workaround.  It would be better if inquirer call would leave the event loop running unless it created its own event loop.
